/* Generated by Yosys 0.34+43 (git sha1 d21c464ae, gcc 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

(* hdlname = "\\counter" *)
(* top =  1  *)
(* src = "src/modules/counter.sv:1.1-20.10" *)
module counter(clk, rst, count);
  (* src = "src/modules/counter.sv:2.16-2.19" *)
  input clk;
  wire clk;
  wire clk_IBUF_I_O;
  (* src = "src/modules/counter.sv:4.22-4.27" *)
  output [3:0] count;
  wire [3:0] count;
  wire count_OBUF_O_1_I;
  wire count_OBUF_O_2_I;
  wire count_OBUF_O_3_I;
  wire count_OBUF_O_I;
  (* src = "src/modules/counter.sv:3.16-3.19" *)
  input rst;
  wire rst;
  wire rst_IBUF_I_O;
  (* src = "src/modules/counter.sv:7.17-7.21" *)
  wire [3:0] temp;
  (* force_downto = 32'd1 *)
  (* src = "src/modules/counter.sv:12.21-12.29|/usr/local/bin/../share/yosys/gowin/arith_map.v:52.24-52.25" *)
  wire [3:0] temp_ALU_I1_3_COUT;
  (* force_downto = 32'd1 *)
  (* src = "src/modules/counter.sv:12.21-12.29|/usr/local/bin/../share/yosys/gowin/arith_map.v:38.25-38.27" *)
  (* unused_bits = "3" *)
  wire [3:0] temp_ALU_I1_COUT;
  wire temp_ALU_I1_I3;
  (* force_downto = 32'd1 *)
  (* src = "src/modules/counter.sv:12.21-12.29|/usr/local/bin/../share/yosys/gowin/arith_map.v:34.28-34.29" *)
  wire [3:0] temp_DFFC_Q_D;
  (* keep = 32'd1 *)
  IBUF clk_IBUF_I (
    .I(clk),
    .O(clk_IBUF_I_O)
  );
  (* keep = 32'd1 *)
  OBUF count_OBUF_O (
    .I(count_OBUF_O_I),
    .O(count[3])
  );
  (* keep = 32'd1 *)
  OBUF count_OBUF_O_1 (
    .I(count_OBUF_O_1_I),
    .O(count[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:135.23-136.15" *)
  LUT1 #(
    .INIT(2'h1)
  ) count_OBUF_O_1_I_LUT1_F (
    .F(count_OBUF_O_1_I),
    .I0(temp[2])
  );
  (* keep = 32'd1 *)
  OBUF count_OBUF_O_2 (
    .I(count_OBUF_O_2_I),
    .O(count[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:135.23-136.15" *)
  LUT1 #(
    .INIT(2'h1)
  ) count_OBUF_O_2_I_LUT1_F (
    .F(count_OBUF_O_2_I),
    .I0(temp[1])
  );
  (* keep = 32'd1 *)
  OBUF count_OBUF_O_3 (
    .I(count_OBUF_O_3_I),
    .O(count[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:135.23-136.15" *)
  LUT1 #(
    .INIT(2'h1)
  ) count_OBUF_O_3_I_LUT1_F (
    .F(count_OBUF_O_3_I),
    .I0(temp[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:135.23-136.15" *)
  LUT1 #(
    .INIT(2'h1)
  ) count_OBUF_O_I_LUT1_F (
    .F(count_OBUF_O_I),
    .I0(temp[3])
  );
  (* keep = 32'd1 *)
  IBUF rst_IBUF_I (
    .I(rst),
    .O(rst_IBUF_I_O)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/counter.sv:12.21-12.29|/usr/local/bin/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'd2)
  ) temp_ALU_I1 (
    .CIN(temp_ALU_I1_COUT[2]),
    .COUT(temp_ALU_I1_COUT[3]),
    .I0(temp_ALU_I1_3_COUT[0]),
    .I1(temp[3]),
    .I3(temp_ALU_I1_I3),
    .SUM(temp_DFFC_Q_D[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/counter.sv:12.21-12.29|/usr/local/bin/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'd2)
  ) temp_ALU_I1_1 (
    .CIN(temp_ALU_I1_COUT[1]),
    .COUT(temp_ALU_I1_COUT[2]),
    .I0(temp_ALU_I1_3_COUT[0]),
    .I1(temp[2]),
    .I3(temp_ALU_I1_I3),
    .SUM(temp_DFFC_Q_D[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/counter.sv:12.21-12.29|/usr/local/bin/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'd2)
  ) temp_ALU_I1_2 (
    .CIN(temp_ALU_I1_COUT[0]),
    .COUT(temp_ALU_I1_COUT[1]),
    .I0(temp_ALU_I1_3_COUT[0]),
    .I1(temp[1]),
    .I3(temp_ALU_I1_I3),
    .SUM(temp_DFFC_Q_D[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/counter.sv:12.21-12.29|/usr/local/bin/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'd2)
  ) temp_ALU_I1_3 (
    .CIN(temp_ALU_I1_3_COUT[0]),
    .COUT(temp_ALU_I1_COUT[0]),
    .I0(temp_ALU_I1_I3),
    .I1(temp[0]),
    .I3(temp_ALU_I1_I3),
    .SUM(temp_DFFC_Q_D[0])
  );
  GND temp_ALU_I1_3_COUT_GND_G (
    .G(temp_ALU_I1_3_COUT[0])
  );
  VCC temp_ALU_I1_I3_VCC_V (
    .V(temp_ALU_I1_I3)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/counter.sv:8.5-14.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:91.7-91.59" *)
  DFFC temp_DFFC_Q (
    .CLEAR(rst_IBUF_I_O),
    .CLK(clk_IBUF_I_O),
    .D(temp_DFFC_Q_D[3]),
    .Q(temp[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/counter.sv:8.5-14.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:91.7-91.59" *)
  DFFC temp_DFFC_Q_1 (
    .CLEAR(rst_IBUF_I_O),
    .CLK(clk_IBUF_I_O),
    .D(temp_DFFC_Q_D[2]),
    .Q(temp[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/counter.sv:8.5-14.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:91.7-91.59" *)
  DFFC temp_DFFC_Q_2 (
    .CLEAR(rst_IBUF_I_O),
    .CLK(clk_IBUF_I_O),
    .D(temp_DFFC_Q_D[1]),
    .Q(temp[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/counter.sv:8.5-14.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:91.7-91.59" *)
  DFFC temp_DFFC_Q_3 (
    .CLEAR(rst_IBUF_I_O),
    .CLK(clk_IBUF_I_O),
    .D(temp_DFFC_Q_D[0]),
    .Q(temp[0])
  );
  assign temp_ALU_I1_3_COUT[3] = temp_ALU_I1_COUT[2];
  assign temp_ALU_I1_3_COUT[2] = temp_ALU_I1_COUT[1];
  assign temp_ALU_I1_3_COUT[1] = temp_ALU_I1_COUT[0];
endmodule
