/* Generated by Yosys 0.44 (git sha1 80ba43d26, g++ 14.2.1 -march=x86-64 -mtune=generic -O2 -fno-plt -fexceptions -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -ffile-prefix-map=/build/yosys/src=/usr/src/debug/yosys -fPIC -O3) */

(* hdlname = "counter" *)
(* top =  1  *)
(* src = "src/modules/counter.sv:1.1-20.10" *)
module counter(clk, rst, count);
  (* src = "src/modules/counter.sv:2.16-2.19" *)
  input clk;
  wire clk;
  wire clk_IBUF_I_O;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:130.20-130.21" *)
  wire clk_IBUF_I_O_DFFC_CLK_1_Q;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:130.20-130.21" *)
  wire clk_IBUF_I_O_DFFC_CLK_2_Q;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:130.20-130.21" *)
  wire clk_IBUF_I_O_DFFC_CLK_3_Q;
  (* unused_bits = "0" *)
  wire clk_IBUF_I_O_DFFC_CLK_3_Q_ALU_I1_SUM;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:130.20-130.21" *)
  wire clk_IBUF_I_O_DFFC_CLK_Q;
  (* src = "src/modules/counter.sv:4.22-4.27" *)
  output [3:0] count;
  wire [3:0] count;
  (* force_downto = 32'd1 *)
  (* src = "src/modules/counter.sv:12.21-12.29|/usr/bin/../share/yosys/gowin/arith_map.v:34.28-34.29" *)
  wire [3:0] count_OBUF_O_3_I;
  (* abc9_carry = 32'd1 *)
  (* src = "src/modules/counter.sv:12.21-12.29|/usr/bin/../share/yosys/gowin/arith_map.v:57.7-63.5|/usr/bin/../share/yosys/gowin/cells_sim.v:886.25-886.29" *)
  wire count_OBUF_O_3_I_ALU_SUM_1_COUT;
  (* abc9_carry = 32'd1 *)
  (* src = "src/modules/counter.sv:12.21-12.29|/usr/bin/../share/yosys/gowin/arith_map.v:57.7-63.5|/usr/bin/../share/yosys/gowin/cells_sim.v:886.25-886.29" *)
  wire count_OBUF_O_3_I_ALU_SUM_2_CIN;
  (* abc9_carry = 32'd1 *)
  (* src = "src/modules/counter.sv:12.21-12.29|/usr/bin/../share/yosys/gowin/arith_map.v:57.7-63.5|/usr/bin/../share/yosys/gowin/cells_sim.v:886.25-886.29" *)
  wire count_OBUF_O_3_I_ALU_SUM_2_COUT;
  (* abc9_carry = 32'd1 *)
  (* src = "src/modules/counter.sv:12.21-12.29|/usr/bin/../share/yosys/gowin/arith_map.v:57.7-63.5|/usr/bin/../share/yosys/gowin/cells_sim.v:886.25-886.29" *)
  (* unused_bits = "0" *)
  wire count_OBUF_O_3_I_ALU_SUM_COUT;
  wire count_OBUF_O_3_I_ALU_SUM_I0;
  wire count_OBUF_O_3_I_ALU_SUM_I3;
  wire [3:0] count_OBUF_O_I;
  (* src = "src/modules/counter.sv:3.16-3.19" *)
  input rst;
  wire rst;
  wire rst_IBUF_I_O;
  (* keep = 32'd1 *)
  IBUF clk_IBUF_I (
    .I(clk),
    .O(clk_IBUF_I_O)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/counter.sv:8.5-14.8|/usr/bin/../share/yosys/gowin/cells_map.v:91.7-91.59" *)
  DFFC clk_IBUF_I_O_DFFC_CLK (
    .CLEAR(rst_IBUF_I_O),
    .CLK(clk_IBUF_I_O),
    .D(count_OBUF_O_3_I[3]),
    .Q(clk_IBUF_I_O_DFFC_CLK_Q)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/counter.sv:8.5-14.8|/usr/bin/../share/yosys/gowin/cells_map.v:91.7-91.59" *)
  DFFC clk_IBUF_I_O_DFFC_CLK_1 (
    .CLEAR(rst_IBUF_I_O),
    .CLK(clk_IBUF_I_O),
    .D(count_OBUF_O_3_I[2]),
    .Q(clk_IBUF_I_O_DFFC_CLK_1_Q)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/counter.sv:8.5-14.8|/usr/bin/../share/yosys/gowin/cells_map.v:91.7-91.59" *)
  DFFC clk_IBUF_I_O_DFFC_CLK_2 (
    .CLEAR(rst_IBUF_I_O),
    .CLK(clk_IBUF_I_O),
    .D(count_OBUF_O_3_I[1]),
    .Q(clk_IBUF_I_O_DFFC_CLK_2_Q)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/counter.sv:8.5-14.8|/usr/bin/../share/yosys/gowin/cells_map.v:91.7-91.59" *)
  DFFC clk_IBUF_I_O_DFFC_CLK_3 (
    .CLEAR(rst_IBUF_I_O),
    .CLK(clk_IBUF_I_O),
    .D(count_OBUF_O_I[0]),
    .Q(clk_IBUF_I_O_DFFC_CLK_3_Q)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/counter.sv:12.21-12.29|/usr/bin/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'd2)
  ) clk_IBUF_I_O_DFFC_CLK_3_Q_ALU_I1 (
    .CIN(count_OBUF_O_3_I_ALU_SUM_I0),
    .COUT(count_OBUF_O_3_I_ALU_SUM_2_CIN),
    .I0(count_OBUF_O_3_I_ALU_SUM_I3),
    .I1(clk_IBUF_I_O_DFFC_CLK_3_Q),
    .I3(count_OBUF_O_3_I_ALU_SUM_I3),
    .SUM(clk_IBUF_I_O_DFFC_CLK_3_Q_ALU_I1_SUM)
  );
  (* keep = 32'd1 *)
  OBUF count_OBUF_O (
    .I(count_OBUF_O_I[3]),
    .O(count[3])
  );
  (* keep = 32'd1 *)
  OBUF count_OBUF_O_1 (
    .I(count_OBUF_O_I[2]),
    .O(count[2])
  );
  (* keep = 32'd1 *)
  OBUF count_OBUF_O_2 (
    .I(count_OBUF_O_I[1]),
    .O(count[1])
  );
  (* keep = 32'd1 *)
  OBUF count_OBUF_O_3 (
    .I(count_OBUF_O_I[0]),
    .O(count[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/counter.sv:12.21-12.29|/usr/bin/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'd2)
  ) count_OBUF_O_3_I_ALU_SUM (
    .CIN(count_OBUF_O_3_I_ALU_SUM_1_COUT),
    .COUT(count_OBUF_O_3_I_ALU_SUM_COUT),
    .I0(count_OBUF_O_3_I_ALU_SUM_I0),
    .I1(clk_IBUF_I_O_DFFC_CLK_Q),
    .I3(count_OBUF_O_3_I_ALU_SUM_I3),
    .SUM(count_OBUF_O_3_I[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/counter.sv:12.21-12.29|/usr/bin/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'd2)
  ) count_OBUF_O_3_I_ALU_SUM_1 (
    .CIN(count_OBUF_O_3_I_ALU_SUM_2_COUT),
    .COUT(count_OBUF_O_3_I_ALU_SUM_1_COUT),
    .I0(count_OBUF_O_3_I_ALU_SUM_I0),
    .I1(clk_IBUF_I_O_DFFC_CLK_1_Q),
    .I3(count_OBUF_O_3_I_ALU_SUM_I3),
    .SUM(count_OBUF_O_3_I[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/counter.sv:12.21-12.29|/usr/bin/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'd2)
  ) count_OBUF_O_3_I_ALU_SUM_2 (
    .CIN(count_OBUF_O_3_I_ALU_SUM_2_CIN),
    .COUT(count_OBUF_O_3_I_ALU_SUM_2_COUT),
    .I0(count_OBUF_O_3_I_ALU_SUM_I0),
    .I1(clk_IBUF_I_O_DFFC_CLK_2_Q),
    .I3(count_OBUF_O_3_I_ALU_SUM_I3),
    .SUM(count_OBUF_O_3_I[1])
  );
  GND count_OBUF_O_3_I_ALU_SUM_I0_GND_G (
    .G(count_OBUF_O_3_I_ALU_SUM_I0)
  );
  VCC count_OBUF_O_3_I_ALU_SUM_I3_VCC_V (
    .V(count_OBUF_O_3_I_ALU_SUM_I3)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:135.23-136.15" *)
  LUT1 #(
    .INIT(2'h1)
  ) count_OBUF_O_3_I_LUT1_F (
    .F(count_OBUF_O_I[0]),
    .I0(clk_IBUF_I_O_DFFC_CLK_3_Q)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:135.23-136.15" *)
  LUT1 #(
    .INIT(2'h1)
  ) count_OBUF_O_I_LUT1_F (
    .F(count_OBUF_O_I[3]),
    .I0(clk_IBUF_I_O_DFFC_CLK_Q)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:135.23-136.15" *)
  LUT1 #(
    .INIT(2'h1)
  ) count_OBUF_O_I_LUT1_F_1 (
    .F(count_OBUF_O_I[2]),
    .I0(clk_IBUF_I_O_DFFC_CLK_1_Q)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:135.23-136.15" *)
  LUT1 #(
    .INIT(2'h1)
  ) count_OBUF_O_I_LUT1_F_2 (
    .F(count_OBUF_O_I[1]),
    .I0(clk_IBUF_I_O_DFFC_CLK_2_Q)
  );
  (* keep = 32'd1 *)
  IBUF rst_IBUF_I (
    .I(rst),
    .O(rst_IBUF_I_O)
  );
  assign count_OBUF_O_3_I[0] = count_OBUF_O_I[0];
endmodule
