/* Generated by Yosys 0.44 (git sha1 80ba43d26, g++ 14.2.1 -march=x86-64 -mtune=generic -O2 -fno-plt -fexceptions -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -ffile-prefix-map=/build/yosys/src=/usr/src/debug/yosys -fPIC -O3) */

(* hdlname = "wave_LED" *)
(* top =  1  *)
(* src = "src/modules/wave_LED.sv:1.1-57.10" *)
module wave_LED(clk, signal, LED);
  (* src = "src/modules/wave_LED.sv:4.22-4.25" *)
  output [5:0] LED;
  wire [5:0] LED;
  wire [5:0] LED_OBUF_O_I;
  wire LED_OBUF_O_I_DFFE_Q_1_D;
  wire LED_OBUF_O_I_DFFE_Q_2_D;
  wire LED_OBUF_O_I_DFFE_Q_3_D;
  wire LED_OBUF_O_I_DFFE_Q_4_D;
  wire LED_OBUF_O_I_DFFE_Q_5_D;
  wire LED_OBUF_O_I_DFFE_Q_D;
  (* src = "src/modules/wave_LED.sv:2.16-2.19" *)
  input clk;
  wire clk;
  wire clk_IBUF_I_O;
  (* hdlname = "d_inst LED" *)
  (* src = "src/modules/wave_LED.sv:196.22-196.25" *)
  wire [5:0] \d_inst.LED ;
  wire \d_inst.LED_DFFE_Q_1_D ;
  wire \d_inst.LED_DFFE_Q_2_D ;
  wire \d_inst.LED_DFFE_Q_CE ;
  wire \d_inst.LED_DFFE_Q_D ;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:151.9-151.11" *)
  wire \d_inst.LED_LUT2_I0_1_F ;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:151.13-151.15" *)
  wire \d_inst.LED_LUT2_I0_1_F_MUX2_LUT5_I0_I1 ;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:157.9-157.11" *)
  wire \d_inst.LED_LUT2_I0_1_F_MUX2_LUT5_I0_O ;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:151.9-151.11" *)
  wire \d_inst.LED_LUT2_I0_2_F ;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:151.13-151.15" *)
  wire \d_inst.LED_LUT2_I0_2_F_MUX2_LUT5_I0_I1 ;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:157.9-157.11" *)
  wire \d_inst.LED_LUT2_I0_2_F_MUX2_LUT5_I0_O ;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:151.9-151.11" *)
  wire \d_inst.LED_LUT2_I0_3_F ;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:151.13-151.15" *)
  wire \d_inst.LED_LUT2_I0_3_F_MUX2_LUT5_I0_I1 ;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:157.9-157.11" *)
  wire \d_inst.LED_LUT2_I0_3_F_MUX2_LUT5_I0_O ;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:151.9-151.11" *)
  wire \d_inst.LED_LUT2_I0_F ;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:151.13-151.15" *)
  wire \d_inst.LED_LUT2_I0_F_MUX2_LUT5_I0_I1 ;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:157.9-157.11" *)
  wire \d_inst.LED_LUT2_I0_F_MUX2_LUT5_I0_O ;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:151.9-151.11" *)
  wire \d_inst.LED_LUT3_I0_1_F ;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:151.13-151.15" *)
  wire \d_inst.LED_LUT3_I0_2_F ;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:151.9-151.11" *)
  wire \d_inst.LED_LUT3_I0_3_F ;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:151.13-151.15" *)
  wire \d_inst.LED_LUT3_I0_F ;
  (* hdlname = "d_inst clk" *)
  (* src = "src/modules/wave_LED.sv:194.16-194.19" *)
  wire \d_inst.clk ;
  (* hdlname = "d_inst rst" *)
  (* src = "src/modules/wave_LED.sv:195.16-195.19" *)
  wire \d_inst.rst ;
  (* src = "src/modules/wave_LED.sv:16.12-16.17" *)
  wire [5:0] d_out;
  (* src = "src/modules/wave_LED.sv:10.5-10.16" *)
  wire display_clk;
  wire display_clk_DFF_Q_D;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:151.9-151.11" *)
  wire display_clk_DFF_Q_D_MUX2_LUT5_O_I0;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:151.13-151.15" *)
  wire display_clk_DFF_Q_D_MUX2_LUT5_O_I1;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:130.20-130.21" *)
  wire [4:0] display_clk_DFF_Q_D_MUX2_LUT5_O_S0;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:169.9-169.11" *)
  wire display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/bin/../share/yosys/gowin/cells_map.v:163.9-163.11" *)
  wire display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/bin/../share/yosys/gowin/cells_map.v:157.9-157.11" *)
  wire display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:151.9-151.11" *)
  wire display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:151.13-151.15" *)
  wire display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/bin/../share/yosys/gowin/cells_map.v:157.13-157.15" *)
  wire display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:151.9-151.11" *)
  wire display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:151.13-151.15" *)
  wire display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/bin/../share/yosys/gowin/cells_map.v:163.13-163.15" *)
  wire display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/bin/../share/yosys/gowin/cells_map.v:157.9-157.11" *)
  wire display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:151.9-151.11" *)
  wire display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:151.13-151.15" *)
  wire display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/bin/../share/yosys/gowin/cells_map.v:157.13-157.15" *)
  wire display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:151.9-151.11" *)
  wire display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:151.13-151.15" *)
  wire display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:169.13-169.15" *)
  wire display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/bin/../share/yosys/gowin/cells_map.v:163.9-163.11" *)
  wire display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/bin/../share/yosys/gowin/cells_map.v:157.9-157.11" *)
  wire display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:151.9-151.11" *)
  wire display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:151.13-151.15" *)
  wire display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/bin/../share/yosys/gowin/cells_map.v:157.13-157.15" *)
  wire display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:151.9-151.11" *)
  wire display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:151.13-151.15" *)
  wire display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/bin/../share/yosys/gowin/cells_map.v:163.13-163.15" *)
  wire display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/bin/../share/yosys/gowin/cells_map.v:157.9-157.11" *)
  wire display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:151.9-151.11" *)
  wire display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:151.13-151.15" *)
  wire display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/bin/../share/yosys/gowin/cells_map.v:157.13-157.15" *)
  wire display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:151.9-151.11" *)
  wire display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:151.13-151.15" *)
  wire display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1;
  (* src = "src/modules/wave_LED.sv:8.11-8.26" *)
  wire [15:0] display_counter;
  wire display_counter_DFFR_Q_10_D;
  (* abc9_carry = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:33.27-33.46|/usr/bin/../share/yosys/gowin/arith_map.v:57.7-63.5|/usr/bin/../share/yosys/gowin/cells_sim.v:886.25-886.29" *)
  wire display_counter_DFFR_Q_10_D_ALU_SUM_COUT;
  wire display_counter_DFFR_Q_11_D;
  (* abc9_carry = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:33.27-33.46|/usr/bin/../share/yosys/gowin/arith_map.v:57.7-63.5|/usr/bin/../share/yosys/gowin/cells_sim.v:886.25-886.29" *)
  wire display_counter_DFFR_Q_11_D_ALU_SUM_COUT;
  wire display_counter_DFFR_Q_12_D;
  (* abc9_carry = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:33.27-33.46|/usr/bin/../share/yosys/gowin/arith_map.v:57.7-63.5|/usr/bin/../share/yosys/gowin/cells_sim.v:886.25-886.29" *)
  wire display_counter_DFFR_Q_12_D_ALU_SUM_COUT;
  wire display_counter_DFFR_Q_13_D;
  (* abc9_carry = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:33.27-33.46|/usr/bin/../share/yosys/gowin/arith_map.v:57.7-63.5|/usr/bin/../share/yosys/gowin/cells_sim.v:886.25-886.29" *)
  wire display_counter_DFFR_Q_13_D_ALU_SUM_COUT;
  wire display_counter_DFFR_Q_14_D;
  (* abc9_carry = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:33.27-33.46|/usr/bin/../share/yosys/gowin/arith_map.v:57.7-63.5|/usr/bin/../share/yosys/gowin/cells_sim.v:886.25-886.29" *)
  wire display_counter_DFFR_Q_14_D_ALU_SUM_CIN;
  (* unused_bits = "0" *)
  wire display_counter_DFFR_Q_14_D_ALU_SUM_CIN_ALU_COUT_SUM;
  (* abc9_carry = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:33.27-33.46|/usr/bin/../share/yosys/gowin/arith_map.v:57.7-63.5|/usr/bin/../share/yosys/gowin/cells_sim.v:886.25-886.29" *)
  wire display_counter_DFFR_Q_14_D_ALU_SUM_COUT;
  wire display_counter_DFFR_Q_15_D;
  wire display_counter_DFFR_Q_1_D;
  (* abc9_carry = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:33.27-33.46|/usr/bin/../share/yosys/gowin/arith_map.v:57.7-63.5|/usr/bin/../share/yosys/gowin/cells_sim.v:886.25-886.29" *)
  wire display_counter_DFFR_Q_1_D_ALU_SUM_COUT;
  wire display_counter_DFFR_Q_2_D;
  (* abc9_carry = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:33.27-33.46|/usr/bin/../share/yosys/gowin/arith_map.v:57.7-63.5|/usr/bin/../share/yosys/gowin/cells_sim.v:886.25-886.29" *)
  wire display_counter_DFFR_Q_2_D_ALU_SUM_COUT;
  wire display_counter_DFFR_Q_3_D;
  (* abc9_carry = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:33.27-33.46|/usr/bin/../share/yosys/gowin/arith_map.v:57.7-63.5|/usr/bin/../share/yosys/gowin/cells_sim.v:886.25-886.29" *)
  wire display_counter_DFFR_Q_3_D_ALU_SUM_COUT;
  wire display_counter_DFFR_Q_4_D;
  (* abc9_carry = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:33.27-33.46|/usr/bin/../share/yosys/gowin/arith_map.v:57.7-63.5|/usr/bin/../share/yosys/gowin/cells_sim.v:886.25-886.29" *)
  wire display_counter_DFFR_Q_4_D_ALU_SUM_COUT;
  wire display_counter_DFFR_Q_5_D;
  (* abc9_carry = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:33.27-33.46|/usr/bin/../share/yosys/gowin/arith_map.v:57.7-63.5|/usr/bin/../share/yosys/gowin/cells_sim.v:886.25-886.29" *)
  wire display_counter_DFFR_Q_5_D_ALU_SUM_COUT;
  wire display_counter_DFFR_Q_6_D;
  (* abc9_carry = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:33.27-33.46|/usr/bin/../share/yosys/gowin/arith_map.v:57.7-63.5|/usr/bin/../share/yosys/gowin/cells_sim.v:886.25-886.29" *)
  wire display_counter_DFFR_Q_6_D_ALU_SUM_COUT;
  wire display_counter_DFFR_Q_7_D;
  (* abc9_carry = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:33.27-33.46|/usr/bin/../share/yosys/gowin/arith_map.v:57.7-63.5|/usr/bin/../share/yosys/gowin/cells_sim.v:886.25-886.29" *)
  wire display_counter_DFFR_Q_7_D_ALU_SUM_COUT;
  wire display_counter_DFFR_Q_8_D;
  (* abc9_carry = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:33.27-33.46|/usr/bin/../share/yosys/gowin/arith_map.v:57.7-63.5|/usr/bin/../share/yosys/gowin/cells_sim.v:886.25-886.29" *)
  wire display_counter_DFFR_Q_8_D_ALU_SUM_COUT;
  wire display_counter_DFFR_Q_9_D;
  (* abc9_carry = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:33.27-33.46|/usr/bin/../share/yosys/gowin/arith_map.v:57.7-63.5|/usr/bin/../share/yosys/gowin/cells_sim.v:886.25-886.29" *)
  wire display_counter_DFFR_Q_9_D_ALU_SUM_COUT;
  wire display_counter_DFFR_Q_D;
  (* abc9_carry = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:33.27-33.46|/usr/bin/../share/yosys/gowin/arith_map.v:57.7-63.5|/usr/bin/../share/yosys/gowin/cells_sim.v:886.25-886.29" *)
  (* unused_bits = "0" *)
  wire display_counter_DFFR_Q_D_ALU_SUM_COUT;
  (* hdlname = "l_inst LED" *)
  (* src = "src/modules/wave_LED.sv:112.22-112.25" *)
  wire [5:0] \l_inst.LED ;
  wire \l_inst.LED_DFFE_Q_1_D ;
  wire \l_inst.LED_DFFE_Q_2_D ;
  wire \l_inst.LED_DFFE_Q_3_D ;
  wire \l_inst.LED_DFFE_Q_4_D ;
  wire \l_inst.LED_DFFE_Q_5_D ;
  wire \l_inst.LED_DFFE_Q_CE ;
  wire \l_inst.LED_DFFE_Q_D ;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:151.9-151.11" *)
  wire \l_inst.LED_LUT2_I0_1_F ;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:157.13-157.15" *)
  wire \l_inst.LED_LUT2_I0_1_F_MUX2_LUT5_I0_O ;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:151.9-151.11" *)
  wire \l_inst.LED_LUT2_I0_2_F ;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:157.13-157.15" *)
  wire \l_inst.LED_LUT2_I0_2_F_MUX2_LUT5_I0_O ;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:151.9-151.11" *)
  wire \l_inst.LED_LUT2_I0_3_F ;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:157.13-157.15" *)
  wire \l_inst.LED_LUT2_I0_3_F_MUX2_LUT5_I0_O ;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:151.9-151.11" *)
  wire \l_inst.LED_LUT2_I0_F ;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:157.13-157.15" *)
  wire \l_inst.LED_LUT2_I0_F_MUX2_LUT5_I0_O ;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:157.9-157.11" *)
  wire \l_inst.LED_MUX2_LUT5_S0_1_O ;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:157.13-157.15" *)
  wire \l_inst.LED_MUX2_LUT5_S0_2_O ;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:157.9-157.11" *)
  wire \l_inst.LED_MUX2_LUT5_S0_3_O ;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:157.13-157.15" *)
  wire \l_inst.LED_MUX2_LUT5_S0_O ;
  (* hdlname = "l_inst clk" *)
  (* src = "src/modules/wave_LED.sv:110.16-110.19" *)
  wire \l_inst.clk ;
  (* hdlname = "l_inst rst" *)
  (* src = "src/modules/wave_LED.sv:111.16-111.19" *)
  wire \l_inst.rst ;
  (* src = "src/modules/wave_LED.sv:13.12-13.17" *)
  wire [5:0] l_out;
  (* hdlname = "r_inst LED" *)
  (* src = "src/modules/wave_LED.sv:63.22-63.25" *)
  wire [5:0] \r_inst.LED ;
  (* hdlname = "r_inst clk" *)
  (* src = "src/modules/wave_LED.sv:61.16-61.19" *)
  wire \r_inst.clk ;
  (* hdlname = "r_inst rst" *)
  (* src = "src/modules/wave_LED.sv:62.16-62.19" *)
  wire \r_inst.rst ;
  (* hdlname = "r_inst state" *)
  (* src = "src/modules/wave_LED.sv:66.11-66.16" *)
  wire [2:0] \r_inst.state ;
  (* src = "src/modules/wave_LED.sv:14.12-14.17" *)
  wire [5:0] r_out;
  (* src = "src/modules/wave_LED.sv:3.20-3.26" *)
  input [2:0] signal;
  wire [2:0] signal;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:130.20-130.21" *)
  wire [5:0] signal_IBUF_I_O;
  (* src = "src/modules/wave_LED.sv:11.5-11.19" *)
  wire start_sequence;
  wire start_sequence_DFFCE_CLEAR_5_CE;
  (* force_downto = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:0.0-0.0|src/modules/wave_LED.sv:119.9-151.16|/usr/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire [2:0] start_sequence_DFFCE_CLEAR_5_D;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:130.20-130.21" *)
  wire [2:0] start_sequence_DFFCE_CLEAR_5_Q;
  wire start_sequence_DFFCE_CLEAR_8_CE;
  (* force_downto = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:0.0-0.0|src/modules/wave_LED.sv:166.9-188.16|/usr/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire [2:0] start_sequence_DFFCE_CLEAR_8_D;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:130.20-130.21" *)
  wire [2:0] start_sequence_DFFCE_CLEAR_8_Q;
  wire start_sequence_DFFCE_CLEAR_CE;
  (* force_downto = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:0.0-0.0|src/modules/wave_LED.sv:203.9-225.16|/usr/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire [2:0] start_sequence_DFFCE_CLEAR_D;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:130.20-130.21" *)
  wire [2:0] start_sequence_DFFCE_CLEAR_Q;
  wire start_sequence_DFF_Q_D;
  (* hdlname = "u_inst LED" *)
  (* src = "src/modules/wave_LED.sv:159.22-159.25" *)
  wire [5:0] \u_inst.LED ;
  wire \u_inst.LED_DFFE_Q_1_D ;
  wire \u_inst.LED_DFFE_Q_2_D ;
  wire \u_inst.LED_DFFE_Q_CE ;
  wire \u_inst.LED_DFFE_Q_D ;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:151.13-151.15" *)
  wire \u_inst.LED_LUT2_I0_1_F ;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:151.13-151.15" *)
  wire \u_inst.LED_LUT2_I0_2_F ;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:151.13-151.15" *)
  wire \u_inst.LED_LUT2_I0_3_F ;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:151.13-151.15" *)
  wire \u_inst.LED_LUT2_I0_F ;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:151.9-151.11" *)
  wire \u_inst.LED_LUT3_I0_1_F ;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:151.13-151.15" *)
  wire \u_inst.LED_LUT3_I0_2_F ;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:151.9-151.11" *)
  wire \u_inst.LED_LUT3_I0_3_F ;
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:151.13-151.15" *)
  wire \u_inst.LED_LUT3_I0_F ;
  (* hdlname = "u_inst clk" *)
  (* src = "src/modules/wave_LED.sv:157.16-157.19" *)
  wire \u_inst.clk ;
  (* hdlname = "u_inst rst" *)
  (* src = "src/modules/wave_LED.sv:158.16-158.19" *)
  wire \u_inst.rst ;
  (* src = "src/modules/wave_LED.sv:15.12-15.17" *)
  wire [5:0] u_out;
  (* keep = 32'd1 *)
  OBUF LED_OBUF_O (
    .I(LED_OBUF_O_I[5]),
    .O(LED[5])
  );
  (* keep = 32'd1 *)
  OBUF LED_OBUF_O_1 (
    .I(LED_OBUF_O_I[4]),
    .O(LED[4])
  );
  (* keep = 32'd1 *)
  OBUF LED_OBUF_O_2 (
    .I(LED_OBUF_O_I[3]),
    .O(LED[3])
  );
  (* keep = 32'd1 *)
  OBUF LED_OBUF_O_3 (
    .I(LED_OBUF_O_I[2]),
    .O(LED[2])
  );
  (* keep = 32'd1 *)
  OBUF LED_OBUF_O_4 (
    .I(LED_OBUF_O_I[1]),
    .O(LED[1])
  );
  (* keep = 32'd1 *)
  OBUF LED_OBUF_O_5 (
    .I(LED_OBUF_O_I[0]),
    .O(LED[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:39.1-54.4|/usr/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE LED_OBUF_O_I_DFFE_Q (
    .CE(start_sequence_DFF_Q_D),
    .CLK(clk_IBUF_I_O),
    .D(LED_OBUF_O_I_DFFE_Q_D),
    .Q(LED_OBUF_O_I[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:39.1-54.4|/usr/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE LED_OBUF_O_I_DFFE_Q_1 (
    .CE(start_sequence_DFF_Q_D),
    .CLK(clk_IBUF_I_O),
    .D(LED_OBUF_O_I_DFFE_Q_1_D),
    .Q(LED_OBUF_O_I[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:160.14-160.54" *)
  MUX2_LUT6 LED_OBUF_O_I_DFFE_Q_1_D_MUX2_LUT6_O (
    .I0(\d_inst.LED_LUT2_I0_3_F_MUX2_LUT5_I0_O ),
    .I1(\l_inst.LED_LUT2_I0_3_F_MUX2_LUT5_I0_O ),
    .O(LED_OBUF_O_I_DFFE_Q_1_D),
    .S0(signal_IBUF_I_O[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:39.1-54.4|/usr/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE LED_OBUF_O_I_DFFE_Q_2 (
    .CE(start_sequence_DFF_Q_D),
    .CLK(clk_IBUF_I_O),
    .D(LED_OBUF_O_I_DFFE_Q_2_D),
    .Q(LED_OBUF_O_I[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:160.14-160.54" *)
  MUX2_LUT6 LED_OBUF_O_I_DFFE_Q_2_D_MUX2_LUT6_O (
    .I0(\d_inst.LED_LUT2_I0_2_F_MUX2_LUT5_I0_O ),
    .I1(\l_inst.LED_LUT2_I0_2_F_MUX2_LUT5_I0_O ),
    .O(LED_OBUF_O_I_DFFE_Q_2_D),
    .S0(signal_IBUF_I_O[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:39.1-54.4|/usr/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE LED_OBUF_O_I_DFFE_Q_3 (
    .CE(start_sequence_DFF_Q_D),
    .CLK(clk_IBUF_I_O),
    .D(LED_OBUF_O_I_DFFE_Q_3_D),
    .Q(LED_OBUF_O_I[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:160.14-160.54" *)
  MUX2_LUT6 LED_OBUF_O_I_DFFE_Q_3_D_MUX2_LUT6_O (
    .I0(\d_inst.LED_LUT2_I0_1_F_MUX2_LUT5_I0_O ),
    .I1(\l_inst.LED_LUT2_I0_1_F_MUX2_LUT5_I0_O ),
    .O(LED_OBUF_O_I_DFFE_Q_3_D),
    .S0(signal_IBUF_I_O[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:39.1-54.4|/usr/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE LED_OBUF_O_I_DFFE_Q_4 (
    .CE(start_sequence_DFF_Q_D),
    .CLK(clk_IBUF_I_O),
    .D(LED_OBUF_O_I_DFFE_Q_4_D),
    .Q(LED_OBUF_O_I[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:39.1-54.4|/usr/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE LED_OBUF_O_I_DFFE_Q_5 (
    .CE(start_sequence_DFF_Q_D),
    .CLK(clk_IBUF_I_O),
    .D(LED_OBUF_O_I_DFFE_Q_5_D),
    .Q(LED_OBUF_O_I[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:160.14-160.54" *)
  MUX2_LUT6 LED_OBUF_O_I_DFFE_Q_D_MUX2_LUT6_O (
    .I0(\d_inst.LED_LUT2_I0_F_MUX2_LUT5_I0_O ),
    .I1(\l_inst.LED_LUT2_I0_F_MUX2_LUT5_I0_O ),
    .O(LED_OBUF_O_I_DFFE_Q_D),
    .S0(signal_IBUF_I_O[5])
  );
  (* keep = 32'd1 *)
  IBUF clk_IBUF_I (
    .I(clk),
    .O(clk_IBUF_I_O)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:199.1-227.4|/usr/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \d_inst.LED_DFFE_Q  (
    .CE(\d_inst.LED_DFFE_Q_CE ),
    .CLK(\u_inst.clk ),
    .D(\d_inst.LED_DFFE_Q_D ),
    .Q(signal_IBUF_I_O[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:199.1-227.4|/usr/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \d_inst.LED_DFFE_Q_1  (
    .CE(\d_inst.LED_DFFE_Q_CE ),
    .CLK(\u_inst.clk ),
    .D(\d_inst.LED_DFFE_Q_1_D ),
    .Q(d_out[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:143.23-144.37" *)
  LUT3 #(
    .INIT(8'h20)
  ) \d_inst.LED_DFFE_Q_1_D_LUT3_F  (
    .F(\d_inst.LED_DFFE_Q_1_D ),
    .I0(start_sequence_DFFCE_CLEAR_Q[0]),
    .I1(start_sequence_DFFCE_CLEAR_Q[1]),
    .I2(start_sequence_DFFCE_CLEAR_Q[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:199.1-227.4|/usr/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \d_inst.LED_DFFE_Q_2  (
    .CE(\d_inst.LED_DFFE_Q_CE ),
    .CLK(\u_inst.clk ),
    .D(\d_inst.LED_DFFE_Q_2_D ),
    .Q(d_out[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:143.23-144.37" *)
  LUT3 #(
    .INIT(8'h10)
  ) \d_inst.LED_DFFE_Q_2_D_LUT3_F  (
    .F(\d_inst.LED_DFFE_Q_2_D ),
    .I0(start_sequence_DFFCE_CLEAR_Q[0]),
    .I1(start_sequence_DFFCE_CLEAR_Q[1]),
    .I2(start_sequence_DFFCE_CLEAR_Q[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:139.23-140.26" *)
  LUT2 #(
    .INIT(4'h1)
  ) \d_inst.LED_DFFE_Q_CE_LUT2_F  (
    .F(\d_inst.LED_DFFE_Q_CE ),
    .I0(\u_inst.rst ),
    .I1(start_sequence_DFFCE_CLEAR_Q[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:143.23-144.37" *)
  LUT3 #(
    .INIT(8'h02)
  ) \d_inst.LED_DFFE_Q_D_LUT3_F  (
    .F(\d_inst.LED_DFFE_Q_D ),
    .I0(start_sequence_DFFCE_CLEAR_Q[0]),
    .I1(start_sequence_DFFCE_CLEAR_Q[1]),
    .I2(start_sequence_DFFCE_CLEAR_Q[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:152.41-152.66|/usr/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT2 #(
    .INIT(4'h8)
  ) \d_inst.LED_LUT2_I0  (
    .F(\d_inst.LED_LUT2_I0_F ),
    .I0(d_out[0]),
    .I1(signal_IBUF_I_O[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:152.41-152.66|/usr/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT2 #(
    .INIT(4'h8)
  ) \d_inst.LED_LUT2_I0_1  (
    .F(\d_inst.LED_LUT2_I0_1_F ),
    .I0(d_out[2]),
    .I1(signal_IBUF_I_O[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:154.14-154.54" *)
  MUX2_LUT5 \d_inst.LED_LUT2_I0_1_F_MUX2_LUT5_I0  (
    .I0(\d_inst.LED_LUT2_I0_1_F ),
    .I1(\d_inst.LED_LUT2_I0_1_F_MUX2_LUT5_I0_I1 ),
    .O(\d_inst.LED_LUT2_I0_1_F_MUX2_LUT5_I0_O ),
    .S0(signal_IBUF_I_O[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:153.41-153.66|/usr/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT1 #(
    .INIT(2'h0)
  ) \d_inst.LED_LUT2_I0_1_F_MUX2_LUT5_I0_I1_LUT1_F  (
    .F(\d_inst.LED_LUT2_I0_1_F_MUX2_LUT5_I0_I1 ),
    .I0(r_out[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:152.41-152.66|/usr/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT2 #(
    .INIT(4'h8)
  ) \d_inst.LED_LUT2_I0_2  (
    .F(\d_inst.LED_LUT2_I0_2_F ),
    .I0(d_out[2]),
    .I1(signal_IBUF_I_O[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:154.14-154.54" *)
  MUX2_LUT5 \d_inst.LED_LUT2_I0_2_F_MUX2_LUT5_I0  (
    .I0(\d_inst.LED_LUT2_I0_2_F ),
    .I1(\d_inst.LED_LUT2_I0_2_F_MUX2_LUT5_I0_I1 ),
    .O(\d_inst.LED_LUT2_I0_2_F_MUX2_LUT5_I0_O ),
    .S0(signal_IBUF_I_O[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:153.41-153.66|/usr/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT1 #(
    .INIT(2'h0)
  ) \d_inst.LED_LUT2_I0_2_F_MUX2_LUT5_I0_I1_LUT1_F  (
    .F(\d_inst.LED_LUT2_I0_2_F_MUX2_LUT5_I0_I1 ),
    .I0(r_out[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:152.41-152.66|/usr/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT2 #(
    .INIT(4'h8)
  ) \d_inst.LED_LUT2_I0_3  (
    .F(\d_inst.LED_LUT2_I0_3_F ),
    .I0(signal_IBUF_I_O[0]),
    .I1(signal_IBUF_I_O[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:154.14-154.54" *)
  MUX2_LUT5 \d_inst.LED_LUT2_I0_3_F_MUX2_LUT5_I0  (
    .I0(\d_inst.LED_LUT2_I0_3_F ),
    .I1(\d_inst.LED_LUT2_I0_3_F_MUX2_LUT5_I0_I1 ),
    .O(\d_inst.LED_LUT2_I0_3_F_MUX2_LUT5_I0_O ),
    .S0(signal_IBUF_I_O[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:153.41-153.66|/usr/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT1 #(
    .INIT(2'h0)
  ) \d_inst.LED_LUT2_I0_3_F_MUX2_LUT5_I0_I1_LUT1_F  (
    .F(\d_inst.LED_LUT2_I0_3_F_MUX2_LUT5_I0_I1 ),
    .I0(r_out[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:154.14-154.54" *)
  MUX2_LUT5 \d_inst.LED_LUT2_I0_F_MUX2_LUT5_I0  (
    .I0(\d_inst.LED_LUT2_I0_F ),
    .I1(\d_inst.LED_LUT2_I0_F_MUX2_LUT5_I0_I1 ),
    .O(\d_inst.LED_LUT2_I0_F_MUX2_LUT5_I0_O ),
    .S0(signal_IBUF_I_O[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:153.41-153.66|/usr/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT1 #(
    .INIT(2'h1)
  ) \d_inst.LED_LUT2_I0_F_MUX2_LUT5_I0_I1_LUT1_F  (
    .F(\d_inst.LED_LUT2_I0_F_MUX2_LUT5_I0_I1 ),
    .I0(signal_IBUF_I_O[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:153.41-153.66|/usr/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT3 #(
    .INIT(8'h08)
  ) \d_inst.LED_LUT3_I0  (
    .F(\d_inst.LED_LUT3_I0_F ),
    .I0(d_out[0]),
    .I1(signal_IBUF_I_O[3]),
    .I2(signal_IBUF_I_O[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:152.41-152.66|/usr/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT3 #(
    .INIT(8'h08)
  ) \d_inst.LED_LUT3_I0_1  (
    .F(\d_inst.LED_LUT3_I0_1_F ),
    .I0(d_out[0]),
    .I1(signal_IBUF_I_O[3]),
    .I2(signal_IBUF_I_O[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:153.41-153.66|/usr/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT3 #(
    .INIT(8'h08)
  ) \d_inst.LED_LUT3_I0_2  (
    .F(\d_inst.LED_LUT3_I0_2_F ),
    .I0(signal_IBUF_I_O[0]),
    .I1(signal_IBUF_I_O[3]),
    .I2(signal_IBUF_I_O[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:152.41-152.66|/usr/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT3 #(
    .INIT(8'h08)
  ) \d_inst.LED_LUT3_I0_3  (
    .F(\d_inst.LED_LUT3_I0_3_F ),
    .I0(signal_IBUF_I_O[0]),
    .I1(signal_IBUF_I_O[3]),
    .I2(signal_IBUF_I_O[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:25.1-37.4|/usr/bin/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF display_clk_DFF_Q (
    .CLK(clk_IBUF_I_O),
    .D(display_clk_DFF_Q_D),
    .Q(\u_inst.clk )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:154.14-154.54" *)
  MUX2_LUT5 display_clk_DFF_Q_D_MUX2_LUT5_O (
    .I0(display_clk_DFF_Q_D_MUX2_LUT5_O_I0),
    .I1(display_clk_DFF_Q_D_MUX2_LUT5_O_I1),
    .O(display_clk_DFF_Q_D),
    .S0(display_clk_DFF_Q_D_MUX2_LUT5_O_S0[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:152.41-152.66|/usr/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT1 #(
    .INIT(2'h0)
  ) display_clk_DFF_Q_D_MUX2_LUT5_O_I0_LUT1_F (
    .F(display_clk_DFF_Q_D_MUX2_LUT5_O_I0),
    .I0(r_out[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:153.41-153.66|/usr/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT4 #(
    .INIT(16'h1000)
  ) display_clk_DFF_Q_D_MUX2_LUT5_O_I1_LUT4_F (
    .F(display_clk_DFF_Q_D_MUX2_LUT5_O_I1),
    .I0(display_counter[5]),
    .I1(display_counter[4]),
    .I2(display_clk_DFF_Q_D_MUX2_LUT5_O_S0[2]),
    .I3(display_clk_DFF_Q_D_MUX2_LUT5_O_S0[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:139.23-140.26" *)
  LUT2 #(
    .INIT(4'h1)
  ) display_clk_DFF_Q_D_MUX2_LUT5_O_S0_LUT2_F (
    .F(display_clk_DFF_Q_D_MUX2_LUT5_O_S0[2]),
    .I0(display_counter[7]),
    .I1(display_counter[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT4 #(
    .INIT(16'h0100)
  ) display_clk_DFF_Q_D_MUX2_LUT5_O_S0_LUT4_F (
    .F(display_clk_DFF_Q_D_MUX2_LUT5_O_S0[3]),
    .I0(display_counter[3]),
    .I1(display_counter[2]),
    .I2(display_counter[1]),
    .I3(display_counter[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:172.14-172.54" *)
  MUX2_LUT8 display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O (
    .I0(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0),
    .I1(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1),
    .O(display_clk_DFF_Q_D_MUX2_LUT5_O_S0[4]),
    .S0(display_counter[8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/bin/../share/yosys/gowin/cells_map.v:166.14-166.54" *)
  MUX2_LUT7 display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O (
    .I0(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0),
    .I1(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1),
    .O(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0),
    .S0(display_counter[9])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/bin/../share/yosys/gowin/cells_map.v:160.14-160.54" *)
  MUX2_LUT6 display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O (
    .I0(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0),
    .I1(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1),
    .O(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0),
    .S0(display_counter[10])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:154.14-154.54" *)
  MUX2_LUT5 display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O (
    .I0(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0),
    .I1(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1),
    .O(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0),
    .S0(display_counter[11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:152.41-152.66|/usr/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT4 #(
    .INIT(16'h0001)
  ) display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0_LUT4_F (
    .F(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0),
    .I0(display_counter[15]),
    .I1(display_counter[14]),
    .I2(display_counter[13]),
    .I3(display_counter[12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:153.41-153.66|/usr/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT1 #(
    .INIT(2'h0)
  ) display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1_LUT1_F (
    .F(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1),
    .I0(r_out[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:154.14-154.54" *)
  MUX2_LUT5 display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O (
    .I0(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0),
    .I1(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1),
    .O(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1),
    .S0(display_counter[11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:152.41-152.66|/usr/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT1 #(
    .INIT(2'h0)
  ) display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0_LUT1_F (
    .F(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0),
    .I0(r_out[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:153.41-153.66|/usr/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT1 #(
    .INIT(2'h0)
  ) display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1_LUT1_F (
    .F(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1),
    .I0(r_out[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/bin/../share/yosys/gowin/cells_map.v:160.14-160.54" *)
  MUX2_LUT6 display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O (
    .I0(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0),
    .I1(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1),
    .O(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1),
    .S0(display_counter[10])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:154.14-154.54" *)
  MUX2_LUT5 display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O (
    .I0(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0),
    .I1(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1),
    .O(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0),
    .S0(display_counter[11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:152.41-152.66|/usr/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT1 #(
    .INIT(2'h0)
  ) display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0_LUT1_F (
    .F(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0),
    .I0(r_out[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:153.41-153.66|/usr/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT1 #(
    .INIT(2'h0)
  ) display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1_LUT1_F (
    .F(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1),
    .I0(r_out[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:154.14-154.54" *)
  MUX2_LUT5 display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O (
    .I0(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0),
    .I1(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1),
    .O(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1),
    .S0(display_counter[11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:152.41-152.66|/usr/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT1 #(
    .INIT(2'h0)
  ) display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0_LUT1_F (
    .F(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0),
    .I0(r_out[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:153.41-153.66|/usr/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT1 #(
    .INIT(2'h0)
  ) display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1_LUT1_F (
    .F(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1),
    .I0(r_out[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/bin/../share/yosys/gowin/cells_map.v:166.14-166.54" *)
  MUX2_LUT7 display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O (
    .I0(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0),
    .I1(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1),
    .O(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1),
    .S0(display_counter[9])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/bin/../share/yosys/gowin/cells_map.v:160.14-160.54" *)
  MUX2_LUT6 display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O (
    .I0(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0),
    .I1(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1),
    .O(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0),
    .S0(display_counter[10])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:154.14-154.54" *)
  MUX2_LUT5 display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O (
    .I0(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0),
    .I1(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1),
    .O(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0),
    .S0(display_counter[11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:152.41-152.66|/usr/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT1 #(
    .INIT(2'h0)
  ) display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0_LUT1_F (
    .F(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0),
    .I0(r_out[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:153.41-153.66|/usr/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT1 #(
    .INIT(2'h0)
  ) display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1_LUT1_F (
    .F(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1),
    .I0(r_out[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:154.14-154.54" *)
  MUX2_LUT5 display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O (
    .I0(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0),
    .I1(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1),
    .O(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1),
    .S0(display_counter[11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:152.41-152.66|/usr/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT1 #(
    .INIT(2'h0)
  ) display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0_LUT1_F (
    .F(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0),
    .I0(r_out[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:153.41-153.66|/usr/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT1 #(
    .INIT(2'h0)
  ) display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1_LUT1_F (
    .F(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1),
    .I0(r_out[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/bin/../share/yosys/gowin/cells_map.v:160.14-160.54" *)
  MUX2_LUT6 display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O (
    .I0(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0),
    .I1(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1),
    .O(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1),
    .S0(display_counter[10])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:154.14-154.54" *)
  MUX2_LUT5 display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O (
    .I0(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0),
    .I1(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1),
    .O(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0),
    .S0(display_counter[11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:152.41-152.66|/usr/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT1 #(
    .INIT(2'h0)
  ) display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0_LUT1_F (
    .F(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0),
    .I0(r_out[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:153.41-153.66|/usr/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT1 #(
    .INIT(2'h0)
  ) display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1_LUT1_F (
    .F(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1),
    .I0(r_out[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:154.14-154.54" *)
  MUX2_LUT5 display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O (
    .I0(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0),
    .I1(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1),
    .O(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1),
    .S0(display_counter[11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:152.41-152.66|/usr/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT1 #(
    .INIT(2'h0)
  ) display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0_LUT1_F (
    .F(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0),
    .I0(r_out[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:153.41-153.66|/usr/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT1 #(
    .INIT(2'h0)
  ) display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1_LUT1_F (
    .F(display_clk_DFF_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1),
    .I0(r_out[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:25.1-37.4|/usr/bin/../share/yosys/gowin/cells_map.v:31.7-31.59" *)
  DFFR display_counter_DFFR_Q (
    .CLK(clk_IBUF_I_O),
    .D(display_counter_DFFR_Q_D),
    .Q(display_counter[15]),
    .RESET(display_clk_DFF_Q_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:25.1-37.4|/usr/bin/../share/yosys/gowin/cells_map.v:31.7-31.59" *)
  DFFR display_counter_DFFR_Q_1 (
    .CLK(clk_IBUF_I_O),
    .D(display_counter_DFFR_Q_1_D),
    .Q(display_counter[14]),
    .RESET(display_clk_DFF_Q_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:25.1-37.4|/usr/bin/../share/yosys/gowin/cells_map.v:31.7-31.59" *)
  DFFR display_counter_DFFR_Q_10 (
    .CLK(clk_IBUF_I_O),
    .D(display_counter_DFFR_Q_10_D),
    .Q(display_counter[5]),
    .RESET(display_clk_DFF_Q_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:33.27-33.46|/usr/bin/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'd2)
  ) display_counter_DFFR_Q_10_D_ALU_SUM (
    .CIN(display_counter_DFFR_Q_11_D_ALU_SUM_COUT),
    .COUT(display_counter_DFFR_Q_10_D_ALU_SUM_COUT),
    .I0(r_out[0]),
    .I1(display_counter[5]),
    .I3(r_out[5]),
    .SUM(display_counter_DFFR_Q_10_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:25.1-37.4|/usr/bin/../share/yosys/gowin/cells_map.v:31.7-31.59" *)
  DFFR display_counter_DFFR_Q_11 (
    .CLK(clk_IBUF_I_O),
    .D(display_counter_DFFR_Q_11_D),
    .Q(display_counter[4]),
    .RESET(display_clk_DFF_Q_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:33.27-33.46|/usr/bin/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'd2)
  ) display_counter_DFFR_Q_11_D_ALU_SUM (
    .CIN(display_counter_DFFR_Q_12_D_ALU_SUM_COUT),
    .COUT(display_counter_DFFR_Q_11_D_ALU_SUM_COUT),
    .I0(r_out[0]),
    .I1(display_counter[4]),
    .I3(r_out[5]),
    .SUM(display_counter_DFFR_Q_11_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:25.1-37.4|/usr/bin/../share/yosys/gowin/cells_map.v:31.7-31.59" *)
  DFFR display_counter_DFFR_Q_12 (
    .CLK(clk_IBUF_I_O),
    .D(display_counter_DFFR_Q_12_D),
    .Q(display_counter[3]),
    .RESET(display_clk_DFF_Q_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:33.27-33.46|/usr/bin/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'd2)
  ) display_counter_DFFR_Q_12_D_ALU_SUM (
    .CIN(display_counter_DFFR_Q_13_D_ALU_SUM_COUT),
    .COUT(display_counter_DFFR_Q_12_D_ALU_SUM_COUT),
    .I0(r_out[0]),
    .I1(display_counter[3]),
    .I3(r_out[5]),
    .SUM(display_counter_DFFR_Q_12_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:25.1-37.4|/usr/bin/../share/yosys/gowin/cells_map.v:31.7-31.59" *)
  DFFR display_counter_DFFR_Q_13 (
    .CLK(clk_IBUF_I_O),
    .D(display_counter_DFFR_Q_13_D),
    .Q(display_counter[2]),
    .RESET(display_clk_DFF_Q_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:33.27-33.46|/usr/bin/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'd2)
  ) display_counter_DFFR_Q_13_D_ALU_SUM (
    .CIN(display_counter_DFFR_Q_14_D_ALU_SUM_COUT),
    .COUT(display_counter_DFFR_Q_13_D_ALU_SUM_COUT),
    .I0(r_out[0]),
    .I1(display_counter[2]),
    .I3(r_out[5]),
    .SUM(display_counter_DFFR_Q_13_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:25.1-37.4|/usr/bin/../share/yosys/gowin/cells_map.v:31.7-31.59" *)
  DFFR display_counter_DFFR_Q_14 (
    .CLK(clk_IBUF_I_O),
    .D(display_counter_DFFR_Q_14_D),
    .Q(display_counter[1]),
    .RESET(display_clk_DFF_Q_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:33.27-33.46|/usr/bin/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'd2)
  ) display_counter_DFFR_Q_14_D_ALU_SUM (
    .CIN(display_counter_DFFR_Q_14_D_ALU_SUM_CIN),
    .COUT(display_counter_DFFR_Q_14_D_ALU_SUM_COUT),
    .I0(r_out[0]),
    .I1(display_counter[1]),
    .I3(r_out[5]),
    .SUM(display_counter_DFFR_Q_14_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:33.27-33.46|/usr/bin/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'd2)
  ) display_counter_DFFR_Q_14_D_ALU_SUM_CIN_ALU_COUT (
    .CIN(r_out[0]),
    .COUT(display_counter_DFFR_Q_14_D_ALU_SUM_CIN),
    .I0(r_out[5]),
    .I1(display_counter[0]),
    .I3(r_out[5]),
    .SUM(display_counter_DFFR_Q_14_D_ALU_SUM_CIN_ALU_COUT_SUM)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:25.1-37.4|/usr/bin/../share/yosys/gowin/cells_map.v:31.7-31.59" *)
  DFFR display_counter_DFFR_Q_15 (
    .CLK(clk_IBUF_I_O),
    .D(display_counter_DFFR_Q_15_D),
    .Q(display_counter[0]),
    .RESET(display_clk_DFF_Q_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:135.23-136.15" *)
  LUT1 #(
    .INIT(2'h1)
  ) display_counter_DFFR_Q_15_D_LUT1_F (
    .F(display_counter_DFFR_Q_15_D),
    .I0(display_counter[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:33.27-33.46|/usr/bin/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'd2)
  ) display_counter_DFFR_Q_1_D_ALU_SUM (
    .CIN(display_counter_DFFR_Q_2_D_ALU_SUM_COUT),
    .COUT(display_counter_DFFR_Q_1_D_ALU_SUM_COUT),
    .I0(r_out[0]),
    .I1(display_counter[14]),
    .I3(r_out[5]),
    .SUM(display_counter_DFFR_Q_1_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:25.1-37.4|/usr/bin/../share/yosys/gowin/cells_map.v:31.7-31.59" *)
  DFFR display_counter_DFFR_Q_2 (
    .CLK(clk_IBUF_I_O),
    .D(display_counter_DFFR_Q_2_D),
    .Q(display_counter[13]),
    .RESET(display_clk_DFF_Q_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:33.27-33.46|/usr/bin/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'd2)
  ) display_counter_DFFR_Q_2_D_ALU_SUM (
    .CIN(display_counter_DFFR_Q_3_D_ALU_SUM_COUT),
    .COUT(display_counter_DFFR_Q_2_D_ALU_SUM_COUT),
    .I0(r_out[0]),
    .I1(display_counter[13]),
    .I3(r_out[5]),
    .SUM(display_counter_DFFR_Q_2_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:25.1-37.4|/usr/bin/../share/yosys/gowin/cells_map.v:31.7-31.59" *)
  DFFR display_counter_DFFR_Q_3 (
    .CLK(clk_IBUF_I_O),
    .D(display_counter_DFFR_Q_3_D),
    .Q(display_counter[12]),
    .RESET(display_clk_DFF_Q_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:33.27-33.46|/usr/bin/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'd2)
  ) display_counter_DFFR_Q_3_D_ALU_SUM (
    .CIN(display_counter_DFFR_Q_4_D_ALU_SUM_COUT),
    .COUT(display_counter_DFFR_Q_3_D_ALU_SUM_COUT),
    .I0(r_out[0]),
    .I1(display_counter[12]),
    .I3(r_out[5]),
    .SUM(display_counter_DFFR_Q_3_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:25.1-37.4|/usr/bin/../share/yosys/gowin/cells_map.v:31.7-31.59" *)
  DFFR display_counter_DFFR_Q_4 (
    .CLK(clk_IBUF_I_O),
    .D(display_counter_DFFR_Q_4_D),
    .Q(display_counter[11]),
    .RESET(display_clk_DFF_Q_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:33.27-33.46|/usr/bin/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'd2)
  ) display_counter_DFFR_Q_4_D_ALU_SUM (
    .CIN(display_counter_DFFR_Q_5_D_ALU_SUM_COUT),
    .COUT(display_counter_DFFR_Q_4_D_ALU_SUM_COUT),
    .I0(r_out[0]),
    .I1(display_counter[11]),
    .I3(r_out[5]),
    .SUM(display_counter_DFFR_Q_4_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:25.1-37.4|/usr/bin/../share/yosys/gowin/cells_map.v:31.7-31.59" *)
  DFFR display_counter_DFFR_Q_5 (
    .CLK(clk_IBUF_I_O),
    .D(display_counter_DFFR_Q_5_D),
    .Q(display_counter[10]),
    .RESET(display_clk_DFF_Q_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:33.27-33.46|/usr/bin/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'd2)
  ) display_counter_DFFR_Q_5_D_ALU_SUM (
    .CIN(display_counter_DFFR_Q_6_D_ALU_SUM_COUT),
    .COUT(display_counter_DFFR_Q_5_D_ALU_SUM_COUT),
    .I0(r_out[0]),
    .I1(display_counter[10]),
    .I3(r_out[5]),
    .SUM(display_counter_DFFR_Q_5_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:25.1-37.4|/usr/bin/../share/yosys/gowin/cells_map.v:31.7-31.59" *)
  DFFR display_counter_DFFR_Q_6 (
    .CLK(clk_IBUF_I_O),
    .D(display_counter_DFFR_Q_6_D),
    .Q(display_counter[9]),
    .RESET(display_clk_DFF_Q_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:33.27-33.46|/usr/bin/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'd2)
  ) display_counter_DFFR_Q_6_D_ALU_SUM (
    .CIN(display_counter_DFFR_Q_7_D_ALU_SUM_COUT),
    .COUT(display_counter_DFFR_Q_6_D_ALU_SUM_COUT),
    .I0(r_out[0]),
    .I1(display_counter[9]),
    .I3(r_out[5]),
    .SUM(display_counter_DFFR_Q_6_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:25.1-37.4|/usr/bin/../share/yosys/gowin/cells_map.v:31.7-31.59" *)
  DFFR display_counter_DFFR_Q_7 (
    .CLK(clk_IBUF_I_O),
    .D(display_counter_DFFR_Q_7_D),
    .Q(display_counter[8]),
    .RESET(display_clk_DFF_Q_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:33.27-33.46|/usr/bin/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'd2)
  ) display_counter_DFFR_Q_7_D_ALU_SUM (
    .CIN(display_counter_DFFR_Q_8_D_ALU_SUM_COUT),
    .COUT(display_counter_DFFR_Q_7_D_ALU_SUM_COUT),
    .I0(r_out[0]),
    .I1(display_counter[8]),
    .I3(r_out[5]),
    .SUM(display_counter_DFFR_Q_7_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:25.1-37.4|/usr/bin/../share/yosys/gowin/cells_map.v:31.7-31.59" *)
  DFFR display_counter_DFFR_Q_8 (
    .CLK(clk_IBUF_I_O),
    .D(display_counter_DFFR_Q_8_D),
    .Q(display_counter[7]),
    .RESET(display_clk_DFF_Q_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:33.27-33.46|/usr/bin/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'd2)
  ) display_counter_DFFR_Q_8_D_ALU_SUM (
    .CIN(display_counter_DFFR_Q_9_D_ALU_SUM_COUT),
    .COUT(display_counter_DFFR_Q_8_D_ALU_SUM_COUT),
    .I0(r_out[0]),
    .I1(display_counter[7]),
    .I3(r_out[5]),
    .SUM(display_counter_DFFR_Q_8_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:25.1-37.4|/usr/bin/../share/yosys/gowin/cells_map.v:31.7-31.59" *)
  DFFR display_counter_DFFR_Q_9 (
    .CLK(clk_IBUF_I_O),
    .D(display_counter_DFFR_Q_9_D),
    .Q(display_counter[6]),
    .RESET(display_clk_DFF_Q_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:33.27-33.46|/usr/bin/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'd2)
  ) display_counter_DFFR_Q_9_D_ALU_SUM (
    .CIN(display_counter_DFFR_Q_10_D_ALU_SUM_COUT),
    .COUT(display_counter_DFFR_Q_9_D_ALU_SUM_COUT),
    .I0(r_out[0]),
    .I1(display_counter[6]),
    .I3(r_out[5]),
    .SUM(display_counter_DFFR_Q_9_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:33.27-33.46|/usr/bin/../share/yosys/gowin/arith_map.v:57.7-63.5" *)
  ALU #(
    .ALU_MODE(32'd2)
  ) display_counter_DFFR_Q_D_ALU_SUM (
    .CIN(display_counter_DFFR_Q_1_D_ALU_SUM_COUT),
    .COUT(display_counter_DFFR_Q_D_ALU_SUM_COUT),
    .I0(r_out[0]),
    .I1(display_counter[15]),
    .I3(r_out[5]),
    .SUM(display_counter_DFFR_Q_D)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:115.1-153.4|/usr/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \l_inst.LED_DFFE_Q  (
    .CE(\l_inst.LED_DFFE_Q_CE ),
    .CLK(\u_inst.clk ),
    .D(\l_inst.LED_DFFE_Q_D ),
    .Q(l_out[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:115.1-153.4|/usr/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \l_inst.LED_DFFE_Q_1  (
    .CE(\l_inst.LED_DFFE_Q_CE ),
    .CLK(\u_inst.clk ),
    .D(\l_inst.LED_DFFE_Q_1_D ),
    .Q(signal_IBUF_I_O[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:143.23-144.37" *)
  LUT3 #(
    .INIT(8'h02)
  ) \l_inst.LED_DFFE_Q_1_D_LUT3_F  (
    .F(\l_inst.LED_DFFE_Q_1_D ),
    .I0(start_sequence_DFFCE_CLEAR_5_Q[0]),
    .I1(start_sequence_DFFCE_CLEAR_5_Q[1]),
    .I2(start_sequence_DFFCE_CLEAR_5_Q[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:115.1-153.4|/usr/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \l_inst.LED_DFFE_Q_2  (
    .CE(\l_inst.LED_DFFE_Q_CE ),
    .CLK(\u_inst.clk ),
    .D(\l_inst.LED_DFFE_Q_2_D ),
    .Q(l_out[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:143.23-144.37" *)
  LUT3 #(
    .INIT(8'h40)
  ) \l_inst.LED_DFFE_Q_2_D_LUT3_F  (
    .F(\l_inst.LED_DFFE_Q_2_D ),
    .I0(start_sequence_DFFCE_CLEAR_5_Q[0]),
    .I1(start_sequence_DFFCE_CLEAR_5_Q[1]),
    .I2(start_sequence_DFFCE_CLEAR_5_Q[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:115.1-153.4|/usr/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \l_inst.LED_DFFE_Q_3  (
    .CE(\l_inst.LED_DFFE_Q_CE ),
    .CLK(\u_inst.clk ),
    .D(\l_inst.LED_DFFE_Q_3_D ),
    .Q(l_out[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:143.23-144.37" *)
  LUT3 #(
    .INIT(8'h10)
  ) \l_inst.LED_DFFE_Q_3_D_LUT3_F  (
    .F(\l_inst.LED_DFFE_Q_3_D ),
    .I0(start_sequence_DFFCE_CLEAR_5_Q[0]),
    .I1(start_sequence_DFFCE_CLEAR_5_Q[1]),
    .I2(start_sequence_DFFCE_CLEAR_5_Q[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:115.1-153.4|/usr/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \l_inst.LED_DFFE_Q_4  (
    .CE(\l_inst.LED_DFFE_Q_CE ),
    .CLK(\u_inst.clk ),
    .D(\l_inst.LED_DFFE_Q_4_D ),
    .Q(l_out[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:143.23-144.37" *)
  LUT3 #(
    .INIT(8'h04)
  ) \l_inst.LED_DFFE_Q_4_D_LUT3_F  (
    .F(\l_inst.LED_DFFE_Q_4_D ),
    .I0(start_sequence_DFFCE_CLEAR_5_Q[0]),
    .I1(start_sequence_DFFCE_CLEAR_5_Q[1]),
    .I2(start_sequence_DFFCE_CLEAR_5_Q[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:115.1-153.4|/usr/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \l_inst.LED_DFFE_Q_5  (
    .CE(\l_inst.LED_DFFE_Q_CE ),
    .CLK(\u_inst.clk ),
    .D(\l_inst.LED_DFFE_Q_5_D ),
    .Q(l_out[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:143.23-144.37" *)
  LUT3 #(
    .INIT(8'h81)
  ) \l_inst.LED_DFFE_Q_5_D_LUT3_F  (
    .F(\l_inst.LED_DFFE_Q_5_D ),
    .I0(start_sequence_DFFCE_CLEAR_5_Q[0]),
    .I1(start_sequence_DFFCE_CLEAR_5_Q[1]),
    .I2(start_sequence_DFFCE_CLEAR_5_Q[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:143.23-144.37" *)
  LUT3 #(
    .INIT(8'h08)
  ) \l_inst.LED_DFFE_Q_D_LUT3_F  (
    .F(\l_inst.LED_DFFE_Q_D ),
    .I0(start_sequence_DFFCE_CLEAR_5_Q[0]),
    .I1(start_sequence_DFFCE_CLEAR_5_Q[1]),
    .I2(start_sequence_DFFCE_CLEAR_5_Q[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:152.41-152.66|/usr/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT2 #(
    .INIT(4'h2)
  ) \l_inst.LED_LUT2_I0  (
    .F(\l_inst.LED_LUT2_I0_F ),
    .I0(l_out[5]),
    .I1(signal_IBUF_I_O[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:152.41-152.66|/usr/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT2 #(
    .INIT(4'h2)
  ) \l_inst.LED_LUT2_I0_1  (
    .F(\l_inst.LED_LUT2_I0_1_F ),
    .I0(l_out[2]),
    .I1(signal_IBUF_I_O[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:154.14-154.54" *)
  MUX2_LUT5 \l_inst.LED_LUT2_I0_1_F_MUX2_LUT5_I0  (
    .I0(\l_inst.LED_LUT2_I0_1_F ),
    .I1(\u_inst.LED_LUT2_I0_1_F ),
    .O(\l_inst.LED_LUT2_I0_1_F_MUX2_LUT5_I0_O ),
    .S0(signal_IBUF_I_O[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:152.41-152.66|/usr/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT2 #(
    .INIT(4'h2)
  ) \l_inst.LED_LUT2_I0_2  (
    .F(\l_inst.LED_LUT2_I0_2_F ),
    .I0(l_out[3]),
    .I1(signal_IBUF_I_O[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:154.14-154.54" *)
  MUX2_LUT5 \l_inst.LED_LUT2_I0_2_F_MUX2_LUT5_I0  (
    .I0(\l_inst.LED_LUT2_I0_2_F ),
    .I1(\u_inst.LED_LUT2_I0_2_F ),
    .O(\l_inst.LED_LUT2_I0_2_F_MUX2_LUT5_I0_O ),
    .S0(signal_IBUF_I_O[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:152.41-152.66|/usr/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT2 #(
    .INIT(4'h2)
  ) \l_inst.LED_LUT2_I0_3  (
    .F(\l_inst.LED_LUT2_I0_3_F ),
    .I0(signal_IBUF_I_O[2]),
    .I1(signal_IBUF_I_O[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:154.14-154.54" *)
  MUX2_LUT5 \l_inst.LED_LUT2_I0_3_F_MUX2_LUT5_I0  (
    .I0(\l_inst.LED_LUT2_I0_3_F ),
    .I1(\u_inst.LED_LUT2_I0_3_F ),
    .O(\l_inst.LED_LUT2_I0_3_F_MUX2_LUT5_I0_O ),
    .S0(signal_IBUF_I_O[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:154.14-154.54" *)
  MUX2_LUT5 \l_inst.LED_LUT2_I0_F_MUX2_LUT5_I0  (
    .I0(\l_inst.LED_LUT2_I0_F ),
    .I1(\u_inst.LED_LUT2_I0_F ),
    .O(\l_inst.LED_LUT2_I0_F_MUX2_LUT5_I0_O ),
    .S0(signal_IBUF_I_O[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:154.14-154.54" *)
  MUX2_LUT5 \l_inst.LED_MUX2_LUT5_S0  (
    .I0(\u_inst.LED_LUT3_I0_1_F ),
    .I1(\u_inst.LED_LUT3_I0_F ),
    .O(\l_inst.LED_MUX2_LUT5_S0_O ),
    .S0(l_out[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:154.14-154.54" *)
  MUX2_LUT5 \l_inst.LED_MUX2_LUT5_S0_1  (
    .I0(\d_inst.LED_LUT3_I0_1_F ),
    .I1(\d_inst.LED_LUT3_I0_F ),
    .O(\l_inst.LED_MUX2_LUT5_S0_1_O ),
    .S0(l_out[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:154.14-154.54" *)
  MUX2_LUT5 \l_inst.LED_MUX2_LUT5_S0_2  (
    .I0(\u_inst.LED_LUT3_I0_3_F ),
    .I1(\u_inst.LED_LUT3_I0_2_F ),
    .O(\l_inst.LED_MUX2_LUT5_S0_2_O ),
    .S0(l_out[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/bin/../share/yosys/gowin/cells_map.v:154.14-154.54" *)
  MUX2_LUT5 \l_inst.LED_MUX2_LUT5_S0_3  (
    .I0(\d_inst.LED_LUT3_I0_3_F ),
    .I1(\d_inst.LED_LUT3_I0_2_F ),
    .O(\l_inst.LED_MUX2_LUT5_S0_3_O ),
    .S0(l_out[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:160.14-160.54" *)
  MUX2_LUT6 \l_inst.LED_MUX2_LUT5_S0_3_O_MUX2_LUT6_I0  (
    .I0(\l_inst.LED_MUX2_LUT5_S0_3_O ),
    .I1(\l_inst.LED_MUX2_LUT5_S0_2_O ),
    .O(LED_OBUF_O_I_DFFE_Q_4_D),
    .S0(signal_IBUF_I_O[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:160.14-160.54" *)
  MUX2_LUT6 \l_inst.LED_MUX2_LUT5_S0_O_MUX2_LUT6_I1  (
    .I0(\l_inst.LED_MUX2_LUT5_S0_1_O ),
    .I1(\l_inst.LED_MUX2_LUT5_S0_O ),
    .O(LED_OBUF_O_I_DFFE_Q_5_D),
    .S0(signal_IBUF_I_O[5])
  );
  GND \r_inst.LED_GND_G  (
    .G(r_out[0])
  );
  VCC \r_inst.LED_VCC_V  (
    .V(r_out[5])
  );
  (* keep = 32'd1 *)
  IBUF signal_IBUF_I (
    .I(signal[2]),
    .O(signal_IBUF_I_O[3])
  );
  (* keep = 32'd1 *)
  IBUF signal_IBUF_I_1 (
    .I(signal[1]),
    .O(signal_IBUF_I_O[4])
  );
  (* keep = 32'd1 *)
  IBUF signal_IBUF_I_2 (
    .I(signal[0]),
    .O(signal_IBUF_I_O[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:199.1-227.4|/usr/bin/../share/yosys/gowin/cells_map.v:115.8-115.68" *)
  DFFCE start_sequence_DFFCE_CLEAR (
    .CE(start_sequence_DFFCE_CLEAR_CE),
    .CLEAR(\u_inst.rst ),
    .CLK(\u_inst.clk ),
    .D(start_sequence_DFFCE_CLEAR_D[2]),
    .Q(start_sequence_DFFCE_CLEAR_Q[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:199.1-227.4|/usr/bin/../share/yosys/gowin/cells_map.v:115.8-115.68" *)
  DFFCE start_sequence_DFFCE_CLEAR_1 (
    .CE(start_sequence_DFFCE_CLEAR_CE),
    .CLEAR(\u_inst.rst ),
    .CLK(\u_inst.clk ),
    .D(start_sequence_DFFCE_CLEAR_D[1]),
    .Q(start_sequence_DFFCE_CLEAR_Q[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:199.1-227.4|/usr/bin/../share/yosys/gowin/cells_map.v:115.8-115.68" *)
  DFFCE start_sequence_DFFCE_CLEAR_2 (
    .CE(start_sequence_DFFCE_CLEAR_CE),
    .CLEAR(\u_inst.rst ),
    .CLK(\u_inst.clk ),
    .D(start_sequence_DFFCE_CLEAR_D[0]),
    .Q(start_sequence_DFFCE_CLEAR_Q[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:115.1-153.4|/usr/bin/../share/yosys/gowin/cells_map.v:115.8-115.68" *)
  DFFCE start_sequence_DFFCE_CLEAR_3 (
    .CE(start_sequence_DFFCE_CLEAR_5_CE),
    .CLEAR(\u_inst.rst ),
    .CLK(\u_inst.clk ),
    .D(start_sequence_DFFCE_CLEAR_5_D[2]),
    .Q(start_sequence_DFFCE_CLEAR_5_Q[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:115.1-153.4|/usr/bin/../share/yosys/gowin/cells_map.v:115.8-115.68" *)
  DFFCE start_sequence_DFFCE_CLEAR_4 (
    .CE(start_sequence_DFFCE_CLEAR_5_CE),
    .CLEAR(\u_inst.rst ),
    .CLK(\u_inst.clk ),
    .D(start_sequence_DFFCE_CLEAR_5_D[1]),
    .Q(start_sequence_DFFCE_CLEAR_5_Q[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:115.1-153.4|/usr/bin/../share/yosys/gowin/cells_map.v:115.8-115.68" *)
  DFFCE start_sequence_DFFCE_CLEAR_5 (
    .CE(start_sequence_DFFCE_CLEAR_5_CE),
    .CLEAR(\u_inst.rst ),
    .CLK(\u_inst.clk ),
    .D(start_sequence_DFFCE_CLEAR_5_D[0]),
    .Q(start_sequence_DFFCE_CLEAR_5_Q[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:143.23-144.37" *)
  LUT3 #(
    .INIT(8'h7f)
  ) start_sequence_DFFCE_CLEAR_5_CE_LUT3_F (
    .F(start_sequence_DFFCE_CLEAR_5_CE),
    .I0(start_sequence_DFFCE_CLEAR_5_Q[0]),
    .I1(start_sequence_DFFCE_CLEAR_5_Q[1]),
    .I2(start_sequence_DFFCE_CLEAR_5_Q[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:143.23-144.37" *)
  LUT3 #(
    .INIT(8'h3a)
  ) start_sequence_DFFCE_CLEAR_5_D_LUT3_F (
    .F(start_sequence_DFFCE_CLEAR_5_D[2]),
    .I0(start_sequence_DFFCE_CLEAR_5_Q[0]),
    .I1(start_sequence_DFFCE_CLEAR_5_Q[1]),
    .I2(start_sequence_DFFCE_CLEAR_5_Q[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:143.23-144.37" *)
  LUT3 #(
    .INIT(8'ha3)
  ) start_sequence_DFFCE_CLEAR_5_D_LUT3_F_1 (
    .F(start_sequence_DFFCE_CLEAR_5_D[0]),
    .I0(start_sequence_DFFCE_CLEAR_5_Q[0]),
    .I1(start_sequence_DFFCE_CLEAR_5_Q[1]),
    .I2(start_sequence_DFFCE_CLEAR_5_Q[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:143.23-144.37" *)
  LUT3 #(
    .INIT(8'h2c)
  ) start_sequence_DFFCE_CLEAR_5_D_LUT3_F_2 (
    .F(start_sequence_DFFCE_CLEAR_5_D[1]),
    .I0(start_sequence_DFFCE_CLEAR_5_Q[0]),
    .I1(start_sequence_DFFCE_CLEAR_5_Q[1]),
    .I2(start_sequence_DFFCE_CLEAR_5_Q[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:162.1-190.4|/usr/bin/../share/yosys/gowin/cells_map.v:115.8-115.68" *)
  DFFCE start_sequence_DFFCE_CLEAR_6 (
    .CE(start_sequence_DFFCE_CLEAR_8_CE),
    .CLEAR(\u_inst.rst ),
    .CLK(\u_inst.clk ),
    .D(start_sequence_DFFCE_CLEAR_8_D[2]),
    .Q(start_sequence_DFFCE_CLEAR_8_Q[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:162.1-190.4|/usr/bin/../share/yosys/gowin/cells_map.v:115.8-115.68" *)
  DFFCE start_sequence_DFFCE_CLEAR_7 (
    .CE(start_sequence_DFFCE_CLEAR_8_CE),
    .CLEAR(\u_inst.rst ),
    .CLK(\u_inst.clk ),
    .D(start_sequence_DFFCE_CLEAR_8_D[1]),
    .Q(start_sequence_DFFCE_CLEAR_8_Q[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:162.1-190.4|/usr/bin/../share/yosys/gowin/cells_map.v:115.8-115.68" *)
  DFFCE start_sequence_DFFCE_CLEAR_8 (
    .CE(start_sequence_DFFCE_CLEAR_8_CE),
    .CLEAR(\u_inst.rst ),
    .CLK(\u_inst.clk ),
    .D(start_sequence_DFFCE_CLEAR_8_D[0]),
    .Q(start_sequence_DFFCE_CLEAR_8_Q[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:143.23-144.37" *)
  LUT3 #(
    .INIT(8'h7f)
  ) start_sequence_DFFCE_CLEAR_8_CE_LUT3_F (
    .F(start_sequence_DFFCE_CLEAR_8_CE),
    .I0(start_sequence_DFFCE_CLEAR_8_Q[0]),
    .I1(start_sequence_DFFCE_CLEAR_8_Q[1]),
    .I2(start_sequence_DFFCE_CLEAR_8_Q[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:139.23-140.26" *)
  LUT2 #(
    .INIT(4'h6)
  ) start_sequence_DFFCE_CLEAR_8_D_LUT2_F (
    .F(start_sequence_DFFCE_CLEAR_8_D[1]),
    .I0(start_sequence_DFFCE_CLEAR_8_Q[1]),
    .I1(start_sequence_DFFCE_CLEAR_8_Q[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:143.23-144.37" *)
  LUT3 #(
    .INIT(8'hb3)
  ) start_sequence_DFFCE_CLEAR_8_D_LUT3_F (
    .F(start_sequence_DFFCE_CLEAR_8_D[0]),
    .I0(start_sequence_DFFCE_CLEAR_8_Q[0]),
    .I1(start_sequence_DFFCE_CLEAR_8_Q[1]),
    .I2(start_sequence_DFFCE_CLEAR_8_Q[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:143.23-144.37" *)
  LUT3 #(
    .INIT(8'h6a)
  ) start_sequence_DFFCE_CLEAR_8_D_LUT3_F_1 (
    .F(start_sequence_DFFCE_CLEAR_8_D[2]),
    .I0(start_sequence_DFFCE_CLEAR_8_Q[0]),
    .I1(start_sequence_DFFCE_CLEAR_8_Q[1]),
    .I2(start_sequence_DFFCE_CLEAR_8_Q[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:143.23-144.37" *)
  LUT3 #(
    .INIT(8'h7f)
  ) start_sequence_DFFCE_CLEAR_CE_LUT3_F (
    .F(start_sequence_DFFCE_CLEAR_CE),
    .I0(start_sequence_DFFCE_CLEAR_Q[0]),
    .I1(start_sequence_DFFCE_CLEAR_Q[1]),
    .I2(start_sequence_DFFCE_CLEAR_Q[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:143.23-144.37" *)
  LUT2 #(
    .INIT(4'h6)
  ) start_sequence_DFFCE_CLEAR_D_LUT2_F (
    .F(start_sequence_DFFCE_CLEAR_D[1]),
    .I0(start_sequence_DFFCE_CLEAR_Q[1]),
    .I1(start_sequence_DFFCE_CLEAR_Q[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:143.23-144.37" *)
  LUT3 #(
    .INIT(8'hb3)
  ) start_sequence_DFFCE_CLEAR_D_LUT3_F (
    .F(start_sequence_DFFCE_CLEAR_D[0]),
    .I0(start_sequence_DFFCE_CLEAR_Q[0]),
    .I1(start_sequence_DFFCE_CLEAR_Q[1]),
    .I2(start_sequence_DFFCE_CLEAR_Q[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:143.23-144.37" *)
  LUT3 #(
    .INIT(8'h6a)
  ) start_sequence_DFFCE_CLEAR_D_LUT3_F_1 (
    .F(start_sequence_DFFCE_CLEAR_D[2]),
    .I0(start_sequence_DFFCE_CLEAR_Q[0]),
    .I1(start_sequence_DFFCE_CLEAR_Q[1]),
    .I2(start_sequence_DFFCE_CLEAR_Q[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:39.1-54.4|/usr/bin/../share/yosys/gowin/cells_map.v:13.6-13.47" *)
  DFF start_sequence_DFF_Q (
    .CLK(clk_IBUF_I_O),
    .D(start_sequence_DFF_Q_D),
    .Q(\u_inst.rst )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:143.23-144.37" *)
  LUT3 #(
    .INIT(8'hfe)
  ) start_sequence_DFF_Q_D_LUT3_F (
    .F(start_sequence_DFF_Q_D),
    .I0(signal_IBUF_I_O[3]),
    .I1(signal_IBUF_I_O[4]),
    .I2(signal_IBUF_I_O[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT4 #(
    .INIT(16'h1555)
  ) start_sequence_LUT4_I0 (
    .F(\l_inst.LED_DFFE_Q_CE ),
    .I0(\u_inst.rst ),
    .I1(start_sequence_DFFCE_CLEAR_5_Q[0]),
    .I2(start_sequence_DFFCE_CLEAR_5_Q[1]),
    .I3(start_sequence_DFFCE_CLEAR_5_Q[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:162.1-190.4|/usr/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \u_inst.LED_DFFE_Q  (
    .CE(\u_inst.LED_DFFE_Q_CE ),
    .CLK(\u_inst.clk ),
    .D(\u_inst.LED_DFFE_Q_D ),
    .Q(u_out[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:162.1-190.4|/usr/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \u_inst.LED_DFFE_Q_1  (
    .CE(\u_inst.LED_DFFE_Q_CE ),
    .CLK(\u_inst.clk ),
    .D(\u_inst.LED_DFFE_Q_1_D ),
    .Q(u_out[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:143.23-144.37" *)
  LUT3 #(
    .INIT(8'hcd)
  ) \u_inst.LED_DFFE_Q_1_D_LUT3_F  (
    .F(\u_inst.LED_DFFE_Q_1_D ),
    .I0(start_sequence_DFFCE_CLEAR_8_Q[0]),
    .I1(start_sequence_DFFCE_CLEAR_8_Q[1]),
    .I2(start_sequence_DFFCE_CLEAR_8_Q[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/modules/wave_LED.sv:162.1-190.4|/usr/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" *)
  DFFE \u_inst.LED_DFFE_Q_2  (
    .CE(\u_inst.LED_DFFE_Q_CE ),
    .CLK(\u_inst.clk ),
    .D(\u_inst.LED_DFFE_Q_2_D ),
    .Q(u_out[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:143.23-144.37" *)
  LUT3 #(
    .INIT(8'h02)
  ) \u_inst.LED_DFFE_Q_2_D_LUT3_F  (
    .F(\u_inst.LED_DFFE_Q_2_D ),
    .I0(start_sequence_DFFCE_CLEAR_8_Q[0]),
    .I1(start_sequence_DFFCE_CLEAR_8_Q[1]),
    .I2(start_sequence_DFFCE_CLEAR_8_Q[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:139.23-140.26" *)
  LUT2 #(
    .INIT(4'h1)
  ) \u_inst.LED_DFFE_Q_CE_LUT2_F  (
    .F(\u_inst.LED_DFFE_Q_CE ),
    .I0(\u_inst.rst ),
    .I1(start_sequence_DFFCE_CLEAR_8_Q[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:143.23-144.37" *)
  LUT3 #(
    .INIT(8'h10)
  ) \u_inst.LED_DFFE_Q_D_LUT3_F  (
    .F(\u_inst.LED_DFFE_Q_D ),
    .I0(start_sequence_DFFCE_CLEAR_8_Q[0]),
    .I1(start_sequence_DFFCE_CLEAR_8_Q[1]),
    .I2(start_sequence_DFFCE_CLEAR_8_Q[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:153.41-153.66|/usr/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT2 #(
    .INIT(4'h2)
  ) \u_inst.LED_LUT2_I0  (
    .F(\u_inst.LED_LUT2_I0_F ),
    .I0(u_out[0]),
    .I1(signal_IBUF_I_O[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:153.41-153.66|/usr/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT2 #(
    .INIT(4'h2)
  ) \u_inst.LED_LUT2_I0_1  (
    .F(\u_inst.LED_LUT2_I0_1_F ),
    .I0(u_out[2]),
    .I1(signal_IBUF_I_O[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:153.41-153.66|/usr/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT2 #(
    .INIT(4'h2)
  ) \u_inst.LED_LUT2_I0_2  (
    .F(\u_inst.LED_LUT2_I0_2_F ),
    .I0(u_out[2]),
    .I1(signal_IBUF_I_O[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:153.41-153.66|/usr/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT2 #(
    .INIT(4'h2)
  ) \u_inst.LED_LUT2_I0_3  (
    .F(\u_inst.LED_LUT2_I0_3_F ),
    .I0(u_out[1]),
    .I1(signal_IBUF_I_O[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:153.41-153.66|/usr/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT3 #(
    .INIT(8'h23)
  ) \u_inst.LED_LUT3_I0  (
    .F(\u_inst.LED_LUT3_I0_F ),
    .I0(u_out[0]),
    .I1(signal_IBUF_I_O[3]),
    .I2(signal_IBUF_I_O[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:152.41-152.66|/usr/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT3 #(
    .INIT(8'h20)
  ) \u_inst.LED_LUT3_I0_1  (
    .F(\u_inst.LED_LUT3_I0_1_F ),
    .I0(u_out[0]),
    .I1(signal_IBUF_I_O[3]),
    .I2(signal_IBUF_I_O[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:153.41-153.66|/usr/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT3 #(
    .INIT(8'h23)
  ) \u_inst.LED_LUT3_I0_2  (
    .F(\u_inst.LED_LUT3_I0_2_F ),
    .I0(u_out[1]),
    .I1(signal_IBUF_I_O[3]),
    .I2(signal_IBUF_I_O[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/bin/../share/yosys/gowin/cells_map.v:152.41-152.66|/usr/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" *)
  LUT3 #(
    .INIT(8'h20)
  ) \u_inst.LED_LUT3_I0_3  (
    .F(\u_inst.LED_LUT3_I0_3_F ),
    .I0(u_out[1]),
    .I1(signal_IBUF_I_O[3]),
    .I2(signal_IBUF_I_O[4])
  );
  assign \d_inst.LED [5] = d_out[0];
  assign \d_inst.LED [4] = signal_IBUF_I_O[0];
  assign \d_inst.LED [3] = d_out[2];
  assign \d_inst.LED [2] = d_out[2];
  assign \d_inst.LED [1] = signal_IBUF_I_O[0];
  assign \d_inst.LED [0] = d_out[0];
  assign \d_inst.clk  = \u_inst.clk ;
  assign \d_inst.rst  = \u_inst.rst ;
  assign d_out[5] = d_out[0];
  assign d_out[4] = signal_IBUF_I_O[0];
  assign d_out[3] = d_out[2];
  assign d_out[1] = signal_IBUF_I_O[0];
  assign display_clk = \u_inst.clk ;
  assign display_clk_DFF_Q_D_MUX2_LUT5_O_S0[1] = display_counter[4];
  assign display_clk_DFF_Q_D_MUX2_LUT5_O_S0[0] = display_counter[5];
  assign \l_inst.LED [5] = l_out[5];
  assign \l_inst.LED [4] = signal_IBUF_I_O[2];
  assign \l_inst.LED [3] = l_out[3];
  assign \l_inst.LED [2] = l_out[2];
  assign \l_inst.LED [1] = l_out[1];
  assign \l_inst.LED [0] = l_out[0];
  assign \l_inst.clk  = \u_inst.clk ;
  assign \l_inst.rst  = \u_inst.rst ;
  assign l_out[4] = signal_IBUF_I_O[2];
  assign \r_inst.LED [5] = r_out[5];
  assign \r_inst.LED [4] = r_out[0];
  assign \r_inst.LED [3] = r_out[0];
  assign \r_inst.LED [2] = r_out[0];
  assign \r_inst.LED [1] = r_out[0];
  assign \r_inst.LED [0] = r_out[0];
  assign \r_inst.clk  = \u_inst.clk ;
  assign \r_inst.rst  = \u_inst.rst ;
  assign \r_inst.state [2] = r_out[0];
  assign \r_inst.state [1] = r_out[0];
  assign \r_inst.state [0] = r_out[0];
  assign r_out[4] = r_out[0];
  assign r_out[3] = r_out[0];
  assign r_out[2] = r_out[0];
  assign r_out[1] = r_out[0];
  assign signal_IBUF_I_O[1] = u_out[1];
  assign start_sequence = \u_inst.rst ;
  assign \u_inst.LED [5] = u_out[0];
  assign \u_inst.LED [4] = u_out[1];
  assign \u_inst.LED [3] = u_out[2];
  assign \u_inst.LED [2] = u_out[2];
  assign \u_inst.LED [1] = u_out[1];
  assign \u_inst.LED [0] = u_out[0];
  assign u_out[5] = u_out[0];
  assign u_out[4] = u_out[1];
  assign u_out[3] = u_out[2];
endmodule
